name: LibsHungergames
main: me.libraryaddict.Hungergames.Hungergames
author: libraryaddict
version: ${project.version}
website: https://github.com/xMarkSt/LibsHungergames
load: STARTUP
softdepend: [LibsDisguises, Vault, TerrainControl, ProtocolLib]
api-version: 1.18